position_controller:
  use_rate_mode: true

  kpxy: 4.0
  kdxy: 4.0

  kpz: 20.0
  kdz: 6.0

  # Attitude control gains
  # roll & pitch
  krp: 4.0
  # yaw
  kyaw: 2.0

  # Position error limits
  pxy_error_max: 0.6
  vxy_error_max: 1.0
  pz_error_max: 0.3
  vz_error_max: 1.0
  yaw_error_max: 0.7

  perform_aerodynamics_compensation: false

  k_drag_x: 0.0
  k_drag_y: 0.0
  k_drag_z: 0.0
  k_thrust_horz: 0.0
